### ISSUE TITLE
date/time is not persistant on a real-time-clock free system.

### ISSUE THREAD

**Issue by fakstory** [nils-werner/raspi-overlayroot#10]
## Question
How can I update the date/time continuously, while keeping overlayroot in action?

This seems to me to be similar to this issue:
https://github.com/nils-werner/raspi-overlayroot/issues/9

Because I would like to be able to let SOME parts of the system writable.
But I have separated them because it is possible that the solution for each is not exactly the same. (I don't have to update the date/time as often as a watchdog)

**Comment by nils-werner** [comment]
Did you try [running an ntp client on boot](https://wiki.archlinux.org/index.php/Network_Time_Protocol_daemon#Synchronize_time_once_per_boot)?

This is something you need to do on a Raspberry Pi, regardless if you use overlayroot or not.

**Comment by fakstory** [comment]
Indeed, I had ntpd running, but not functioning correctly, I have switched to [systemd-timesyncd ](https://wiki.archlinux.org/index.php/systemd-timesyncd) and now it syncs at boot with no problem. 

I would still like a way to make `/var/lib/systemd/timesync/clock` writable.

`Note: The service writes to a local file /var/lib/systemd/timesync/clock with every synchronization. This location is hard-coded and cannot be changed. This may be problematic for running off read-only root partition or trying to minimize writes to an SD card.`

**Comment by nils-werner** [comment]
With overlayroot you should be able to write to `/var/lib/systemd/timesync/clock`! Are you sure you have overlayroot running, and not just set your SD card to read-only?
