### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by hassansofla** [nils-werner/raspi-overlayroot#14]
Could you clarify the installation?
I tried this and did not work:
git clone https://github.com/nils-werner/raspi-overlayroot
makepkg -si

the error was makepkg is not found.

Also, in the method you used, is it still possible to write data to the SD card? I am not talking about power loss transients but in general, when the system is on, can I still write data to the SD card?

**Comment by nils-werner** [comment]
This package is only compatible with Arch Linux. If you don't have the `makepkg` command you probably have a different distribution installed.

Yes, info about writing to the SD card is in the readme.
