### ISSUE TITLE
The overlay prevent me to write to /dev/*

### ISSUE THREAD

**Issue by fakstory** [nils-werner/raspi-overlayroot#9]
# The overlay prevent me to write to /dev/*
I am using overlayroot for a while and I like it. Unfortunately, this was coming with some drawback that I now need to address, and I am not sure how to achieve that the correct way. 

I need to be able to access any devices in /dev, and write to them. This seems impossible to do so when overlayroot is enable. (trying to write to /dev/watchdog0)

Is there a built-in way to achieve that? Or, what would be the better way to do this, while keeping the overlayroot in action?

NOTE: I am aware of the rwrootfs command, which make it works for testing, but I need to be able to continuously write to the watchdog, and NOT in the rwrootfs mode.

**Comment by Lalarian** [comment]
Are you sure than overlayrootfs is fully installed and working correctly at all?
You can normally write to root anywhere with overlayrootfs running, despite the physical drive being read only. That's what overlayrootfs is meant to achieve.

What do you get, whenn issuing 'mount'?
For me it's looking like this:


> proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
> sys on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
> dev on /dev type devtmpfs (rw,nosuid,relatime,size=56940k,nr_inodes=14235,mode=755)
> run on /run type tmpfs (rw,nosuid,nodev,relatime,mode=755)
> overlay on / type overlay (rw,relatime,lowerdir=/overlay/lower,upperdir=/overlay/upper,workdir=/overlay/work)
> overlayroot on /overlay type tmpfs (rw,relatime)
> /dev/sda1 on /overlay/lower type ext2 (ro,relatime,block_validity,barrier,user_xattr,acl)

As I am running a different OS there might be some minor differences, but the principle is same of course.

So as you can see there, the physical flash partition (sda1 in my case) is read only, but the overlay mount on / is rw, and so is /dev.

**Comment by nils-werner** [comment]
As @Lalarian pointed out `/dev/*` files are not real files and do not come from a real filesystem. They cannot be write-protected in a way a filesystem can be

 This is most likely a permissions problem.

**Comment by fakstory** [comment]
Thank you very much, you're right, I was using "sudo" to test, I needed to use "sudo su" to be root first, and then `echo 1 > /dev/watchdog0` worked.

**Comment by nils-werner** [comment]
Maybe did you try

     sudo echo 1 > /dev/watchdog0

?

This won't work as only `echo` will be run as `sudo` and the output redirection `>` won't.

Use

     echo 1 | sudo tee -a /dev/watchdog0

instead.
